<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1521266000478' stop='1521266007475'>
    <name>To test the Angular binding functionality</name>
    <title>To test the Angular binding functionality</title>
    <test-cases>
        <test-case start='1521266000479' status='passed' stop='1521266004221'>
            <name>should not have any previous results</name>
            <title>should not have any previous results</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='bf17b688-9c56-4446-a03b-ce24cb42df6a-attachment.png' type='image/png' size='15605'/>
            </attachments>
        </test-case>
        <test-case start='1521266004221' status='failed' stop='1521266007472'>
            <name>Should display calculation results for performed Arthematic operations and should save results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='0b124e7d-3735-4852-91a8-2b9e71cceb83-attachment.png' type='image/png' size='18208'/>
            </attachments>
            <failure>
                <message>Expected 0 to equal 1.</message>
                <stack-trace>Error: Failed expectation
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\specs\calculation_spec.js:33:28
                    at ManagedPromise.invokeCallback_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at &lt;anonymous>
                    at process._tickCallback (internal/process/next_tick.js:118:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1521266007472' status='pending' stop='1521266007473'>
            <name>Should display calculation results for performed Arthematic operations and should save new results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save new results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Temporarily disabled with xit</message>
                <stack-trace></stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>